### ISSUE TITLE
PSR4 naming standards and Linux compatibility

### ISSUE THREAD

**Issue by Pillarish** [zingchart/ZingChart-PHP#13]
Good day!

We have an issue loading the library into an AWS environment. The autoloader expects class names and file names to match case sensitively. The current zc.php file does not match and therefore does not work for the majority of Linux systems including AWS.

Should be a simple filename change on your side.

Thanks

**Comment by ccoley** [comment]
Thanks for your bug report. This has been fixed in the [v1.0.8](/zingchart/ZingChart-PHP/releases/tag/1.0.8) release.
