### ISSUE TITLE
A lot of private members

### ISSUE THREAD

**Issue by LMCom** [zingchart/ZingChart-PHP#4]
Hi,
I extended the class, but was unable to make something useful with it, since a lot of essential class members are private. Each and every property is private. What's the reasoning behind this?

**Comment by jbogartPint** [comment]
Hi,
I see your point. Thank you for pointing that out. I have now updated the member variables and helper functions to be `protected` as opposed to `private`.

**Comment by LMCom** [comment]
You have my thanks! 👍
