### ISSUE TITLE
getSeriesText() only shows the first label/text

### ISSUE THREAD

**Issue by benjaminfrombe** [zingchart/ZingChart-PHP#5]
When I try to get all labels/texts from my chart, I only get the first one using the getSeriesText() function. Is there a way to find out the names of the other series using a function or is this a bug ?

Thank you 

Benjamin

**Comment by jbogartPint** [comment]
Hi Benjamin,

Good find! Thank you. That certainly was a bug. The functions getSeriesText() and getSeriesData() will now return an array of all the corresponding values.
